---
  - name: Check IP Address
    hosts: routers
    gather_facts: false
    connection: local
    vars:
      cli:
        username: cisco
        password: cisco123!
    
    tasks:
      - name: print ip interfaces
        ios_command: 
          provider: "{{ cli }}"
          commands:
            - show ip interface brief
        register: config
      
      - name: save output to IPs
        copy:
          content: "{{config.stdout[0] }}"
          dest: "IPs/check_ip{{inventory_hostname}}.txt"